title: <center>Rutger Taal</center> # your name (or website title) here
logo: "/images/IMG_5430-min.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My portfolio page
  <br><br>
  <a href="https://www.linkedin.com/in/rutger-taal-48695358/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://bitbucket.org/rutgertaal/">View My BitBucket Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
