<style>
  ul.social-media-list img {
    padding: 5px;
    border-radius: 5px;
    background-color: lightblue;
    width: 36px;
    height: 36px;
  }
  
  ul.social-media-list li {
    display: inline-block;
    margin: 2px;
  }
  
  ul.social-media-list {
    list-style-type: none;
    margin: 0;
    padding: 0;
    font-size: 0px; /* eliminate space between li */
  }
  
  ul.social-media-list img:hover {
    background-color: #63D1F4;
  }
</style>

title: <center>Rutger Taal</center> # your name (or website title) here
logo: "/images/IMG_5430-min.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My portfolio page
  <br><br>
  <a href="https://www.linkedin.com/in/rutger-taal-48695358/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://bitbucket.org/rutgertaal/">View My BitBucket Profile</a>

  <ul class="social-media-list">
      <li><a href="https://twitter.com/mark_heath"><img src="https://unpkg.com/simple-icons@latest/icons/twitter.svg" alt="Twitter" title="Twitter"></a></li>
      <li><a href="https://github.com/markheath"><img src="https://unpkg.com/simple-icons@latest/icons/github.svg" alt="GitHub" title="GitHub"></a></li>
      <li><a href="https://www.pluralsight.com/author/mark-heath"><img src="https://unpkg.com/simple-icons@latest/icons/pluralsight.svg" alt="Pluralsight" title="Pluralsight"></a></a></li>
      <li><a href="https://www.youtube.com/channel/UChV2-HyJ9XzsKLQRztd7Pmw"><img src="https://unpkg.com/simple-icons@latest/icons/youtube.svg" alt="YouTube" title="YouTube"></a></li>
      <li><a href="https://stackoverflow.com/users/7532/mark-heath"><img src="https://unpkg.com/simple-icons@latest/icons/stackoverflow.svg" alt="Stack Overflow" title="Stack Overflow"></a></li>
  </ul>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
